spring:
  application:
    name: linktosync
  jwt:
    secret-key: ${JWT_SECRET_KEY:4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c}
    access-token-expiration: ${JWT_EXPIRATION_TIME}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      jdbc:
        lob:
          non_contextual_creation: true
    open-in-view: false
  logging:
    level:
      '[org.hibernate.SQL]': debug
      com.LinktoSync: DEBUG
  app:
    security:
      username: ${APP_USERNAME}
      password: ${APP_PASSWORD}
  security:
    ignored:
      - /v1/linktosync/api/users/register
  springdoc:
    swagger-ui:
      enabled: ${SWAGGER_UI_ENABLED:true}
  mail:
    host: smtp.gmail.com
    port: 587
    username: linktosyncofficial@gmail.com
    password: xlajhdhnbvjhkpm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # main:
    # allow-bean-definition-overriding: true
