spring:
  application:
    name: linktosync
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      jdbc:
        lob:
          non_contextual_creation: true
    open-in-view: false
  logging:
    level:
      '[org.hibernate.SQL]': debug
      com.LinktoSync: DEBUG
  app:
    security:
      username: ${APP_USERNAME}
      password: ${APP_PASSWORD}
  security:
    ignored:
      - /v1/linktosync/api/users/register
  springdoc:
   swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

  mail:
    host: smtp.gmail.com
    port: 587
    username: linktosyncofficial@gmail.com
    password: xlaj hdhn vbjh kpmm 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
   