spring:
  application:
    name: linktosync
  jwt:
    secret-key: ${JWT_SECRET_KEY:4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c}
    access-token-expiration: ${JWT_EXPIRATION_TIME}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  logging:
    level:
      '[org.hibernate.SQL]': debug
      com.LinktoSync: DEBUG

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liW1KMprOcMkrY5i
            clientSecret: 4414312ae9dcef5045420a2462f17a4787b6ba18
          google:
            clientId: 471245402224-158n2ikgd4k6aen9hhg5jci4dophgnsn.apps.googleusercontent.com
            clientSecret: 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
            # Uncomment and set the scope if needed
            # scope: profile, email
            # redirectUri: "http://localhost:8080/login/oauth2/code/google"

  # Uncomment and configure cache if needed
  # cache:
  #   cache-names: refreshTokenCache
  #   caffeine:
  #     spec: expireAfterWrite=604800000

  springdoc:
    swagger-ui:
      enabled: ${SWAGGER_UI_ENABLED:true}
  mail:
    host: smtp.gmail.com
    port: 587
    username: linktosyncofficial@gmail.com
    password: xlajhdhnbvjhkpm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
